[project]
name = "de-upskills-mock-prj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=2.3.3",
    "polars>=1.44.2",
]

[project.scripts]
de-upskills-mock-prj = "de_upskills_mock_prj:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
